name: mypy

on:
    push:
    pull_request:

jobs:
    checks:
        runs-on : ubuntu-latest
        name    : mypy
        
        steps:
            
        -   uses : actions/checkout@v1
        
        -   name : Navigate To Source
            run  : cd Source
                    
        -   name : Python 3.9 Setup
            uses : actions/setup-python@v1
            with:
                python-version : 3.9
        
        -   name : Install Dependencies
            run  : pip install --requirement requirements.txt

        -   name : MyPy Linter
            run  : mypy --show-column-numbers --hide-error-context .

        -   name : Black Code Formatter
            run  : black .
